services:
    ChorePlanner:
        image: "chrisbesch/chore_planner:2.0.0"
        container_name: "ChorePlanner"

        volumes:
            - "./data:/var/run/data"

        environment:
            ####################
            # Generel Settings #
            ####################
            CHORE_PLANNER_DB_PATH: /var/run/data/chore_planner.sqlite
            # This advances the current week to the next every time the weekly action is performed.
            # set to true for actual deployment
            CHORE_PLANNER_DEBUG: false
            # how many weeks to plan into the future
            CHORE_PLANNER_WEEKS_TO_PLAN: 5
            # probability distribution parameter between in [0, 1]
            # The higher gamma the more extremely the score effects the tenants probability of being
            # chosen for a chore.
            # 0 results the tenant with the highest score to never be picked (unless all tenants have the
            #   same score).
            # 1 results in all tenants having the same probability regardless of their score.
            #
            # See the mathematical proof in docs/probability_distribution.pdf in the repo
            CHORE_PLANNER_GAMMA: 0.0
            # When the chore_planner never ran before or was upgraded to v1.0.0 the chore_planner doesn't know when it ran last.
            # The fallback week is used in this case.
            # When this is true, the last week is used.
            #     This means the chore_planner prints out the weekly message at the first weekly action (i.e., the first SIGHUP), which is what you want.
            # When this is false, the current week is used.
            #     This means the chore_planner only advances the current week at the start of the next week. This should only be used when you upgraded the chore_planner to v1.0.0
            #     and the weekly message for the current week has already been sent.
            CHORE_PLANNER_FALLBACK_TO_LAST_WEEK: true
            # When true the chore_planner tries to exclude busy tenants from chore assignments for this week.
            # Busy tenants are those already doing a chore the last, this or the next week.
            # If you want to prevent the same tenant doing two chores in the same week, enable this.
            CHORE_PLANNER_TRY_EXCLUDE_BUSY_TENANTS: true
            # When should the weekly action be performed?
            # This environment variable is understood by the docker_cron container
            CRON_TIME: "0,30 6 * * *"
            # One of:
            #   Signal
            #   Telegram
            CHORE_PLANNER_CHAT_PROTOCOL: $CHORE_PLANNER_CHAT_PROTOCOL

            #####################
            # Telegram Settings #
            #####################
            # the token of the telegram bot
            TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
            # the id of the chat the bot should listen on
            # Set this to a random value if you don't know your id yet.
            # You'll get an error message telling you the chat_id when the bot receives a new message.
            TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID

            ###################
            # Signal Settings #
            ###################
            SIGNAL_CLI_ENDPOINT: signalcli:42069
            # the id of the group the bot should listen on
            # Set this to a random value if you don't know your id yet.
            # You'll get an error message telling you the chat_id when the bot receives a new message.
            SIGNAL_GROUP_ID: $SIGNAL_GROUP_ID
            # the telephone number of the bot
            # This needs to start with the country code and may not contain spaces.
            SIGNAL_ACCOUNT_NAME: $SIGNAL_ACCOUNT_NAME
            # the name that others will see and use to tag the bot
            # This name must not container spaces or quotes
            SIGNAL_DISPLAY_NAME: "@chore_planner_bot"
            # Should the bot listen to messages from the same number it is registered under?
            # This is useful for testing and when you link your personal number to the bot.
            SIGNAL_ALLOW_MESSAGE_FROM_SELF: true

        # only needed when using signal
        networks: ["signal-net"]
        restart: "unless-stopped"

    # only needed when using signal
    SignalCli:
        image: registry.gitlab.com/packaging/signal-cli/signal-cli-native
        container_name: SignalCli
        command: --config /var/lib/signal-cli daemon --tcp 0.0.0.0:42069
        user: root
        volumes:
            - "./signal_cli:/var/lib/signal-cli"
        tmpfs:
            - "/tmp:exec"
        networks: ["signal-net"]
        restart: "unless-stopped"

    DockerCron:
        image: chrisbesch/docker_cron
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        restart: "unless-stopped"

# only needed when using signal
networks:
    signal-net:
