services:
    ChorePlanner:
        image: "chrisbesch/chore_planner:0.2.0"
        container_name: "ChorePlanner"

        volumes:
            - "./data:/var/run/data"

        environment:
            CHORE_PLANNER_DB_PATH: /var/run/data/chore_planner.sqlite
            # This advances the current week to the next every time the weekly action is performed.
            # set to true for actual deployment
            CHORE_PLANNER_DEBUG: false
            # how many weeks to plan into the future
            CHORE_PLANNER_WEEKS_TO_PLAN: 5
            # probability distribution parameter between in [0, 1]
            # The higher gamma the more extremely the score effects the tenants probability of being
            # chosen for a chore.
            # 0 results the tenant with the highest score to never be picked (unless all tenants have the
            #   same score).
            # 1 results in all tenants having the same probability regardless of their score.
            #
            # See the mathematical proof in docs/probability_distribution.pdf in the repo
            CHORE_PLANNER_GAMMA: 0.0
            # When the chore_planner never ran befor or was upgraded to v1.0.0 the chore_planner doesn't know when it ran last.
            # The fallback week is used in this case.
            # When this is true, the last week is used.
            #     This means the chore_planner prints out the weekly message at the first weekly action (i.e., the first SIGHUP), which is what you want.
            # When this is false, the current week is used.
            #     This means the chore_planner only advances the current week at the start of the next week. This should only be used when you upgraded the chore_planner to v1.0.0
            #     and the weekly message for the current week has already been sent.
            CHORE_PLANNER_FALLBACK_TO_LAST_WEEK: true
            # When true the chore_planner tries to exclude busy tenants from chore assignments for this week.
            # Busy tenants are those already doing a chore the last, this or the next week.
            # If you want to prevent the same tenant doing two chores in the same week, enable this.
            CHORE_PLANNER_TRY_EXCLUDE_BUSY_TENANTS: true
            # the token of the telegram bot
            TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
            # the id of the chat the bot should listen on
            TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID
            # When should the weekly action be performed?
            CRON_TIME: "0,30 6 * * *"

        restart: "unless-stopped"

    DockerCron:
        image: chrisbesch/docker_cron
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"

